# Base URL of the web application
baseUrl: http://localhost:49430

# Backend API
backendScheme: http
backendHost: localhost
backendPort: 8080
backendBasePath: /api

# Configuration of authorization
clientId: backend-service
clientSecret: secret
redirectUrl: com.flutter-auth-test:/oauth-redirect
issuer: http://localhost:8180/realms/quarkus
discoveryUrl: http://localhost:8180/realms/quarkus/protocol/openid-connect/token/introspect
postLogoutRedirectUrl: com.flutter-auth-test:/oauth-logout
scopes:
 - openid
 - profile
 - email
authorizationEndpoint: http://localhost:8180/realms/quarkus/protocol/openid-connect/auth
tokenEndpoint: http://localhost:8180/realms/quarkus/protocol/openid-connect/token
endSessionEndpoint: http://localhost:8180/realms/quarkus/protocol/openid-connect/logout